# Copyright 2018 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: build-pipeline-controller
  namespace: knative-build-pipeline
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: build-pipeline-controller
    spec:
      serviceAccountName: build-pipeline-controller
      containers:
      - name: build-pipeline-controller
        image: github.com/knative/build-pipeline/cmd/controller
        args: [
          "-logtostderr",
          "-stderrthreshold", "INFO",
          "--output-handler-image", "gcr.io/dlorenc-vmtest2/outputs-6ed35446ed4d7b1c10ba0b7c880ae119@sha256:94d1de456ccb100fe8e48dc9c6e053339e2d24435af628ce709e9afe822c700a",
        ]
        volumeMounts:
        - name: config-logging
          mountPath: /etc/config-logging
      volumes:
        - name: config-logging
          configMap:
            name: config-logging
